CREATE VIEW GEMEENTE AS
SELECT 
    DATA_OBJECT.CODE, 
    DATA_GEMEENTE.NAAM, 
    DATA_GEMEENTE.GRENS 
FROM DATA_GEMEENTE 
LEFT OUTER JOIN DATA_OBJECT 
ON DATA_OBJECT.CODE = DATA_GEMEENTE.CODE

CREATE VIEW WOONPLAATS AS
SELECT 
    DATA_OBJECT.CODE,
    DATA_AUTHENTIEK.BEGINGELDIGHEID,
    DATA_AUTHENTIEK.EINDEGELDIGHEID,
    DATA_AUTHENTIEK.DOCUMENTDATUM,
    DATA_AUTHENTIEK.DOCUMENTNUMMER,
    DATA_AUTHENTIEK.INONDERZOEK,
    DATA_WOONPLAATS.NAAM, 
    DATA_WOONPLAATS.STATUS,
    DATA_GEMEENTE.NAAM AS GEMEENTENAAM,
    DATA_WOONPLAATS.GRENS
FROM DATA_WOONPLAATS
LEFT OUTER JOIN DATA_AUTHENTIEK
ON DATA_AUTHENTIEK.CODE = DATA_WOONPLAATS.CODE
LEFT OUTER JOIN DATA_OBJECT 
ON DATA_OBJECT.CODE = DATA_AUTHENTIEK.CODE
LEFT OUTER JOIN DATA_GEMEENTE
ON DATA_GEMEENTE.CODE = DATA_WOONPLAATS.GEMEENTE_CODE
