<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.vrom.nl/bag/stuf/0120"  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.vrom.nl/bag/stuf/0120" name="baglv">
   <import namespace="http://www.vrom.nl/bag/stuf/0120" location="bag-sync-stuf-msg.xsd"/>
   <message name="STUFBAG_Synchronisatie">
      <part name="synchronisatieBericht" element="tns:synchronisatieBericht"/>
   </message>
   <message name="STUFBAG_SynchronisatieAntwoord">
      <part name="synchronisatieAntwoordBericht" element="tns:synchronisatieAntwoordBericht"/>
   </message>
   <message name="StUF_Fout">
      <part name="fout" element="tns:synchronisatieFoutBericht"/>
   </message>
   <portType name="STUFBAG_SynchronisatiePortType">
      <documentation>
			BAG synchronisatieverzoeken zijn synchroon. Met als response een (synchroon)antwoordbericht of een foutbericht.
		</documentation>
      <operation name="verwerkSynchronisatie">
         <input message="tns:STUFBAG_Synchronisatie"/>
         <output message="tns:STUFBAG_SynchronisatieAntwoord"/>
         <fault name="StUF_Sync_Fout" message="tns:StUF_Fout"/>
      </operation>
   </portType>
   <binding name="StUFSOAPBindingSynchroon" type="tns:STUFBAG_SynchronisatiePortType">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="verwerkSynchronisatie">
         <soap:operation soapAction="urn:verwerkSynchronisatie"/>
         <input>
            <soap:body use="literal"/>
         </input>
         <output>
            <soap:body use="literal"/>
         </output>
         <fault name="StUF_Sync_Fout">
            <soap:body use="literal"/>
         </fault>
      </operation>
   </binding>
   <service name="STUFBAGSynchronisatie">
      <port name="STUFBAGSynchronisatiePort" binding="tns:StUFSOAPBindingSynchroon">
         <soap:address location="http://localhost:8080/bag-sync-web/services/BagSyncWebService"/>
      </port>
   </service>
</definitions>
