SELECT 
  DATA_OBJECT.CODE, 
  DATA_OBJECT.BAGOBJECT ,
  DATA_AUTHENTIEK.BEGINGELDIGHEID,
  DATA_AUTHENTIEK.DOCUMENTDATUM,
  DATA_AUTHENTIEK.DOCUMENTNUMMER,
  DATA_AUTHENTIEK.EINDEGELDIGHEID,
  DATA_AUTHENTIEK.INONDERZOEK,
  DATA_AUTHENTIEK.STATUS,
  DATA_WOONPLAATS.NAAM,
  DATA_WOONPLAATS.GRENS
FROM DATA_WOONPLAATS
LEFT OUTER JOIN DATA_AUTHENTIEK
ON DATA_AUTHENTIEK.CODE = DATA_WOONPLAATS.CODE
LEFT OUTER JOIN DATA_OBJECT
ON DATA_OBJECT.CODE = DATA_AUTHENTIEK.CODE
WHERE DATA_AUTHENTIEK.EINDEGELDIGHEID IS NULL