SELECT 
  DATA_OBJECT.CODE, 
  DATA_OBJECT.BAGOBJECT,
  DATA_AUTHENTIEK.BEGINGELDIGHEID,
  DATA_AUTHENTIEK.DOCUMENTDATUM,
  DATA_AUTHENTIEK.DOCUMENTNUMMER,
  DATA_AUTHENTIEK.EINDEGELDIGHEID,
  DATA_AUTHENTIEK.INONDERZOEK,
  DATA_AUTHENTIEK.STATUS,
  DATA_OPENBARERUIMTE.NAAM,
  DATA_OPENBARERUIMTE.TYPE,
  DATA_OPENBARERUIMTE.GRENS
FROM DATA_OPENBARERUIMTE
LEFT OUTER JOIN DATA_AUTHENTIEK
ON DATA_AUTHENTIEK.CODE = DATA_OPENBARERUIMTE.CODE
LEFT OUTER JOIN DATA_OBJECT
ON DATA_OBJECT.CODE = DATA_AUTHENTIEK.CODE
WHERE DATA_AUTHENTIEK.EINDEGELDIGHEID IS NULL